### ISSUE TITLE
things you need to do

### ISSUE THREAD

**Issue by haniali1234** [geekwise-veronica-chavez/geekwise-academy#1]
- two navbar
- name of your index files  (html)

**Comment by haniali1234** [comment]
- page:  about
- issue: footer
- photo
  ![screen shot 2016-03-18 at 11 34 33 am](https://cloud.githubusercontent.com/assets/11038599/13888302/0584d096-ecfe-11e5-9c13-36eb5b9d911d.png)

**Comment by geekwise-veronica-chavez** [comment]
footer is back in but the header nav broke
